-- Ampliação do CMS do site Teacher Flávio
--
-- Execute este arquivo no SQL Editor se supabase_cms.sql já foi aplicado.
-- O script adiciona as demais páginas públicas sem sobrescrever conteúdo editado.

begin;

create index if not exists site_content_updated_by_idx
  on public.site_content (updated_by);

insert into public.site_content
  (key, page_slug, section_slug, label, content_type, value, sort_order)
values
  ('aluno_title', 'aluno', 'cabecalho', 'Título principal', 'text', 'Teacher Flávio', 10),
  ('aluno_enrollment_label', 'aluno', 'menu', 'Texto do botão Matrícula', 'text', 'MATRÍCULA', 20),
  ('aluno_enrollment_url', 'aluno', 'menu', 'Destino do botão Matrícula', 'url', '/matricula/', 30),
  ('aluno_student_area_label', 'aluno', 'menu', 'Texto do botão Área do estudante', 'text', 'ÁREA DO ESTUDANTE', 40),
  ('aluno_student_area_url', 'aluno', 'menu', 'Destino do botão Área do estudante', 'url', '/area-do-estudante/', 50),
  ('aluno_youtube_label', 'aluno', 'menu', 'Texto do botão YouTube', 'text', 'YOUTUBE', 60),
  ('aluno_youtube_url', 'aluno', 'menu', 'Destino do botão YouTube', 'url', 'https://youtube.com/@teacherflavio', 70),
  ('aluno_instagram_label', 'aluno', 'menu', 'Texto do botão Instagram', 'text', 'INSTAGRAM', 80),
  ('aluno_instagram_url', 'aluno', 'menu', 'Destino do botão Instagram', 'url', 'https://www.instagram.com/teacher.flavius', 90),
  ('aluno_professor_label', 'aluno', 'menu', 'Texto do botão Área do professor', 'text', 'ÁREA DO PROFESSOR', 100),
  ('aluno_professor_url', 'aluno', 'menu', 'Destino do botão Área do professor', 'url', '/professor/', 110),

  ('conhecer_student_label', 'quero_conhecer', 'navegacao', 'Texto do botão Área de alunos', 'text', 'Área de alunos', 10),
  ('conhecer_student_url', 'quero_conhecer', 'navegacao', 'Destino do botão Área de alunos', 'url', '/login.html?next=area_do_estudante.html', 20),
  ('conhecer_hero_tag', 'quero_conhecer', 'hero', 'Chamada superior', 'text', '🌍 Inglês que transforma vidas', 30),
  ('conhecer_hero_title', 'quero_conhecer', 'hero', 'Título principal', 'textarea', E'CHEGOU A SUA HORA DE FAZER\nPARTE DO TIME DE ALUNOS DO\nTEACHER FLAVIO', 40),
  ('conhecer_hero_subtitle', 'quero_conhecer', 'hero', 'Texto abaixo do título', 'textarea', 'Assista ao vídeo abaixo para conhecer a metodologia.', 50),
  ('conhecer_video_url', 'quero_conhecer', 'hero', 'Endereço do vídeo', 'url', 'https://www.youtube.com/embed/mZ2GyKKkteI?rel=0', 60),
  ('conhecer_new_class_title', 'quero_conhecer', 'nova_turma', 'Título da nova turma', 'text', 'NOVA TURMA DE INGLÊS', 70),
  ('conhecer_limited_label', 'quero_conhecer', 'nova_turma', 'Aviso de vagas', 'text', 'VAGAS LIMITADAS', 80),
  ('conhecer_question', 'quero_conhecer', 'nova_turma', 'Pergunta de apresentação', 'textarea', 'Você quer aprender inglês de verdade, mesmo que ache que não leva jeito para idiomas?', 90),
  ('conhecer_opportunity_1', 'quero_conhecer', 'nova_turma', 'Texto de oportunidade', 'textarea', 'Então essa pode ser a oportunidade que você estava esperando.', 100),
  ('conhecer_opportunity_2', 'quero_conhecer', 'nova_turma', 'Introdução do público', 'textarea', 'Meu curso foi criado para pessoas que:', 110),
  ('conhecer_audience_1', 'quero_conhecer', 'nova_turma', 'Público 1', 'text', '✔️ nunca estudaram inglês', 120),
  ('conhecer_audience_2', 'quero_conhecer', 'nova_turma', 'Público 2', 'text', '✔️ estudaram mas não conseguem falar', 130),
  ('conhecer_audience_3', 'quero_conhecer', 'nova_turma', 'Público 3', 'text', '✔️ querem aprender de forma simples e prática', 140),
  ('conhecer_benefits_title', 'quero_conhecer', 'beneficios', 'Título dos benefícios', 'text', '📚 O que você vai ter no curso', 150),
  ('conhecer_benefit_1', 'quero_conhecer', 'beneficios', 'Benefício 1', 'text', '✔️ Aulas 100% online', 160),
  ('conhecer_benefit_2', 'quero_conhecer', 'beneficios', 'Benefício 2', 'text', '✔️ Aulas ao vivo', 170),
  ('conhecer_benefit_3', 'quero_conhecer', 'beneficios', 'Benefício 3', 'text', '✔️ Método simples e direto', 180),
  ('conhecer_benefit_4', 'quero_conhecer', 'beneficios', 'Benefício 4', 'text', '✔️ Material de apoio', 190),
  ('conhecer_benefit_5', 'quero_conhecer', 'beneficios', 'Benefício 5', 'text', '✔️ 4 aulas por mês', 200),
  ('conhecer_benefit_6', 'quero_conhecer', 'beneficios', 'Benefício 6', 'text', '✔️ Aulas focadas na prática', 210),
  ('conhecer_benefit_7', 'quero_conhecer', 'beneficios', 'Benefício 7', 'text', '✔️ Aula experimental gratuita', 220),
  ('conhecer_enrollment_label', 'quero_conhecer', 'beneficios', 'Texto do botão Inscrição', 'text', 'FAZER INSCRIÇÃO', 230),
  ('conhecer_enrollment_url', 'quero_conhecer', 'beneficios', 'Destino do botão Inscrição', 'url', '/matricula/', 240),
  ('conhecer_availability_title', 'quero_conhecer', 'disponibilidade', 'Título da disponibilidade', 'text', 'Disponibilidade de vagas', 250),
  ('conhecer_slot_1', 'quero_conhecer', 'disponibilidade', 'Disponibilidade 1', 'text', 'Manhã - 2 vagas', 260),
  ('conhecer_slot_2', 'quero_conhecer', 'disponibilidade', 'Disponibilidade 2', 'text', 'Tarde - 2 vagas', 270),
  ('conhecer_slot_3', 'quero_conhecer', 'disponibilidade', 'Disponibilidade 3', 'text', 'Noite - 3 vagas', 280),
  ('conhecer_availability_highlight', 'quero_conhecer', 'disponibilidade', 'Aviso sobre a turma', 'textarea', '⚠️ A turma é pequena (4 alunos) para garantir acompanhamento individual.', 290),
  ('conhecer_availability_note', 'quero_conhecer', 'disponibilidade', 'Observação sobre as vagas', 'textarea', 'Por isso teremos apenas 4 vagas por turma.', 300),
  ('conhecer_investment_label', 'quero_conhecer', 'investimento', 'Título do investimento', 'text', '💰 INVESTIMENTO', 310),
  ('conhecer_price', 'quero_conhecer', 'investimento', 'Valor da mensalidade', 'text', 'R$99,90/MÊS', 320),
  ('conhecer_registration_note', 'quero_conhecer', 'investimento', 'Aviso sobre inscrições', 'textarea', '⏳ As inscrições ficam abertas até acabar as vagas.', 330),
  ('conhecer_trial_label', 'quero_conhecer', 'investimento', 'Texto do botão Aula experimental', 'text', 'AGENDAR AULA EXPERIMENTAL', 340),
  ('conhecer_trial_url', 'quero_conhecer', 'investimento', 'Destino do botão Aula experimental', 'url', 'https://wa.me/5534998349756?text=Teacher%2C%20quero%20marcar%20uma%20aula%20experimental%20gratuita', 350),
  ('conhecer_instructor_photo', 'quero_conhecer', 'professor', 'Foto do professor', 'image', '/FaceApp_1692762158831%20(1).jpg', 360),
  ('conhecer_instructor_title', 'quero_conhecer', 'professor', 'Título da apresentação', 'text', 'Sobre o professor', 370),
  ('conhecer_instructor_intro', 'quero_conhecer', 'professor', 'Apresentação do professor', 'textarea', 'Eu me chamo Flávio, tenho 34 anos e sou professor de idiomas há 15 anos.', 380),
  ('conhecer_credentials_label', 'quero_conhecer', 'professor', 'Título das formações', 'text', 'Tenho as seguintes formações:', 390),
  ('conhecer_credential_1', 'quero_conhecer', 'professor', 'Formação 1', 'text', '🧑🏻‍🎓 Bacharelado em Tradução', 400),
  ('conhecer_credential_2', 'quero_conhecer', 'professor', 'Formação 2', 'text', '🧑🏻‍🎓 Mestrado em Linguística', 410),
  ('conhecer_credential_3', 'quero_conhecer', 'professor', 'Formação 3', 'text', '🧑🏻‍🎓 Doutorado em Linguística', 420),
  ('conhecer_credential_4', 'quero_conhecer', 'professor', 'Formação 4', 'text', '🧑🏻‍🎓 Certificado Cambridge', 430),
  ('conhecer_instructor_bio', 'quero_conhecer', 'professor', 'Trajetória do professor', 'textarea', 'Durante os meus estudos fiz intercâmbios em Londres, em Roma e em Zurique. Dou aulas e faço traduções dos seguintes idiomas:', 440),
  ('conhecer_language_1', 'quero_conhecer', 'professor', 'Idioma 1', 'text', '🇺🇸 INGLÊS', 450),
  ('conhecer_language_2', 'quero_conhecer', 'professor', 'Idioma 2', 'text', '🇮🇹 ITALIANO', 460),
  ('conhecer_language_3', 'quero_conhecer', 'professor', 'Idioma 3', 'text', '🇩🇪 ALEMÃO', 470),
  ('conhecer_instagram_text', 'quero_conhecer', 'redes_sociais', 'Chamada do Instagram', 'textarea', 'Confira mais sobre meu trabalho em meu Instagram:', 480),
  ('conhecer_instagram_label', 'quero_conhecer', 'redes_sociais', 'Texto do botão Instagram', 'text', 'VER INSTAGRAM', 490),
  ('conhecer_instagram_url', 'quero_conhecer', 'redes_sociais', 'Destino do botão Instagram', 'url', 'https://www.instagram.com/teacher.flavius', 500),

  ('guia_home_label', 'guia_estudante', 'navegacao', 'Texto do botão Início', 'text', '← INÍCIO', 10),
  ('guia_home_url', 'guia_estudante', 'navegacao', 'Destino do botão Início', 'url', '/aluno.html', 20),
  ('guia_hero_tag', 'guia_estudante', 'hero', 'Título superior', 'text', 'GUIA', 30),
  ('guia_hero_subtitle', 'guia_estudante', 'hero', 'Complemento do título', 'text', 'do Estudante', 40),
  ('guia_hero_community', 'guia_estudante', 'hero', 'Texto da comunidade', 'textarea', 'Estamos todos estudando inglês com teacher Flávio', 50),
  ('guia_explore_label', 'guia_estudante', 'hero', 'Texto do botão Explorar', 'text', 'EXPLORE O GUIA', 60),
  ('guia_roteiro_title', 'guia_estudante', 'roteiro', 'Destaque do título', 'text', 'Estudos', 100),
  ('guia_roteiro_how_title', 'guia_estudante', 'roteiro', 'Título Como funciona', 'text', 'Como funciona', 110),
  ('guia_roteiro_how_text', 'guia_estudante', 'roteiro', 'Explicação do roteiro', 'textarea', 'Toda aula você poderá se preparar para uma lição diferente. Comece estudando a lição 1, depois a lição 2 e assim sucessivamente.', 120),
  ('guia_roteiro_notes_text', 'guia_estudante', 'roteiro', 'Orientação sobre anotações', 'textarea', 'Anote todas as palavras e expressões novas em seu caderno.', 130),
  ('guia_roteiro_access_title', 'guia_estudante', 'roteiro', 'Título Acesso ao material', 'text', 'Acesso ao material', 140),
  ('guia_roteiro_video_text', 'guia_estudante', 'roteiro', 'Chamada do vídeo', 'textarea', 'Para entender melhor o que é o Roteiro de Estudos, assista o vídeo abaixo.', 150),
  ('guia_grammar_title', 'guia_estudante', 'gramatica', 'Destaque do título', 'text', 'Gramática', 200),
  ('guia_homework_title', 'guia_estudante', 'tarefas', 'Destaque do título', 'text', 'Casa', 300),
  ('guia_homework_daily_title', 'guia_estudante', 'tarefas', 'Título Prática diária', 'text', 'Prática diária', 310),
  ('guia_homework_previous_title', 'guia_estudante', 'tarefas', 'Título Tarefas anteriores', 'text', 'Tarefas anteriores', 320),
  ('guia_class_title', 'guia_estudante', 'turma_guia', 'Destaque do título', 'text', 'Turma', 400),
  ('guia_class_live_title', 'guia_estudante', 'turma_guia', 'Título Aulas ao vivo', 'text', 'Aulas ao vivo', 410),
  ('guia_class_live_text', 'guia_estudante', 'turma_guia', 'Texto sobre aulas ao vivo', 'textarea', 'Agora você tem um dia e horário marcado para encontrar com seus colegas de turma e a sua turma tem um grupo de WhatsApp.', 420),
  ('guia_class_material_title', 'guia_estudante', 'turma_guia', 'Título Material da aula', 'text', 'Material da aula', 430),
  ('guia_makeup_title', 'guia_estudante', 'reposicao', 'Destaque do título', 'text', 'Aulas', 500),
  ('guia_makeup_how_title', 'guia_estudante', 'reposicao', 'Título Como repor uma aula', 'text', 'Como repor uma aula', 510),
  ('guia_makeup_absence_text', 'guia_estudante', 'reposicao', 'Orientação em caso de ausência', 'textarea', 'Em caso de ausência em alguma aula ao vivo, o aluno não precisa marcar reposição — basta assistir a gravação da aula que faltou.', 520),
  ('guia_makeup_where_title', 'guia_estudante', 'reposicao', 'Título Onde encontrar', 'text', 'Onde encontrar', 530),
  ('guia_notes_title', 'guia_estudante', 'anotacoes', 'Destaque do título', 'text', 'Aulas', 600),
  ('guia_holidays_title', 'guia_estudante', 'feriados', 'Título da seção', 'text', 'Feriados', 700),
  ('guia_holidays_policy_title', 'guia_estudante', 'feriados', 'Título Política de feriados', 'text', 'Política de feriados', 710),
  ('guia_holidays_closed_text', 'guia_estudante', 'feriados', 'Funcionamento em feriados', 'textarea', 'Quando há feriado, a escola não funciona — não tem aulas e nem reposições.', 720),
  ('guia_holidays_compensation_title', 'guia_estudante', 'feriados', 'Título Compensação', 'text', 'Compensação', 730),
  ('guia_cancellations_title', 'guia_estudante', 'cancelamentos', 'Destaque do título', 'text', 'Aulas', 800),
  ('guia_cancellations_teacher_title', 'guia_estudante', 'cancelamentos', 'Título Pelo professor', 'text', 'Pelo professor', 810),
  ('guia_cancellations_student_tech_title', 'guia_estudante', 'cancelamentos', 'Título Problemas técnicos do aluno', 'text', 'Problemas técnicos (aluno)', 820),
  ('guia_cancellations_teacher_tech_title', 'guia_estudante', 'cancelamentos', 'Título Problemas técnicos do professor', 'text', 'Problemas técnicos (professor)', 830),
  ('guia_cancellations_evidence_text', 'guia_estudante', 'cancelamentos', 'Orientação sobre comprovação', 'textarea', 'Para haver reembolso, é preciso que os alunos afetados apresentem provas dos problemas técnicos ocorridos, por meio de capturas de tela, gravações e fotos.', 840),
  ('guia_transfer_title', 'guia_estudante', 'transferencia', 'Destaque do título', 'text', 'Turma', 900),
  ('guia_transfer_how_title', 'guia_estudante', 'transferencia', 'Título Como solicitar', 'text', 'Como solicitar', 910),
  ('guia_transfer_request_text', 'guia_estudante', 'transferencia', 'Orientação para transferência', 'textarea', 'Os alunos poderão solicitar transferência de turma a qualquer momento, desde que haja uma vaga em outra turma.', 920),
  ('guia_transfer_limit_title', 'guia_estudante', 'transferencia', 'Título Limite', 'text', 'Limite', 930),
  ('guia_closure_title', 'guia_estudante', 'encerramento', 'Destaque do título', 'text', 'Cancelamento', 1000),
  ('guia_closure_substitute_title', 'guia_estudante', 'encerramento', 'Título Substituição do professor', 'text', 'Substituição do professor', 1010),
  ('guia_closure_course_title', 'guia_estudante', 'encerramento', 'Título Cancelamento do curso', 'text', 'Cancelamento do curso', 1020),
  ('guia_closure_student_text', 'guia_estudante', 'encerramento', 'Cancelamento pelo aluno', 'textarea', 'A escola não firma contrato com nenhum aluno, portanto, os alunos podem cancelar suas aulas quando quiser e sem apresentar justificativa.', 1030),
  ('guia_closure_school_text', 'guia_estudante', 'encerramento', 'Cancelamento pela escola', 'textarea', 'Do mesmo modo, a escola pode cancelar as aulas dos alunos quando quiser e sem apresentar justificativa.', 1040),
  ('guia_final_alert', 'guia_estudante', 'encerramento', 'Aviso final', 'textarea', '⚖️ OS CASOS E SITUAÇÕES NÃO MENCIONADOS NESTE DOCUMENTO SERÃO ANALISADOS PELA ESCOLA EM CARÁTER DE EXCEPCIONALIDADE.', 1050),
  ('guia_footer_handle', 'guia_estudante', 'redes_sociais', 'Perfil no rodapé', 'text', '@teacher.flavius', 1100)
on conflict (key) do nothing;

commit;
